In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


import warnings
warnings.filterwarnings('ignore')

In [3]:
# Regularization is one of the most important techniques in Machine Learning.
# Reduce overfitting by preventing the model from learning overly complex patterns.

In [5]:
df = sns.load_dataset('mpg')

In [6]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [7]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [8]:
df.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [9]:
df.drop('name' , axis=1 , inplace=True)

In [10]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,18.0,8,307.0,130.0,3504,12.0,70,usa
1,15.0,8,350.0,165.0,3693,11.5,70,usa
2,18.0,8,318.0,150.0,3436,11.0,70,usa
3,16.0,8,304.0,150.0,3433,12.0,70,usa
4,17.0,8,302.0,140.0,3449,10.5,70,usa
...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa
394,44.0,4,97.0,52.0,2130,24.6,82,europe
395,32.0,4,135.0,84.0,2295,11.6,82,usa
396,28.0,4,120.0,79.0,2625,18.6,82,usa
397,31.0,4,119.0,82.0,2720,19.4,82,usa

In [11]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [20]:
df['horsepower'].median()

np.float64(95.0)

In [21]:
df = df.fillna(df['horsepower'].median())

In [22]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    str
dtypes: float64(4), int64(3), str(1)
memory usage: 25.0 KB

In [25]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin              str
dtype: object

In [28]:
df['origin'].value_counts()

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

In [29]:
#convert string column to numerical

df['origin'] = df['origin'].map({'usa' : 1 , 'japan':2 , 'europe' : 3} )

In [36]:
df['origin']= df['origin'].astype(int)

In [37]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin            int64
dtype: object

In [38]:
#separate X and y
X = df.drop('mpg', axis=1)
y = df['mpg']

In [39]:
X

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,8,307.0,130.0,3504,12.0,70,1
1,8,350.0,165.0,3693,11.5,70,1
2,8,318.0,150.0,3436,11.0,70,1
3,8,304.0,150.0,3433,12.0,70,1
4,8,302.0,140.0,3449,10.5,70,1
...,...,...,...,...,...,...,...
393,4,140.0,86.0,2790,15.6,82,1
394,4,97.0,52.0,2130,24.6,82,3
395,4,135.0,84.0,2295,11.6,82,1
396,4,120.0,79.0,2625,18.6,82,1
397,4,119.0,82.0,2720,19.4,82,1

In [40]:
y

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [41]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X, y , test_size=0.25 , random_state=1)

In [42]:
X_train.shape , X_test.shape ,y_train.shape, y_test.shape

((298, 7), (100, 7), (298,), (100,))

In [43]:
#multiple linear regression model
from sklearn.linear_model import LinearRegression
regression_model = LinearRegression()

In [44]:
regression_model

LinearRegression()

In [45]:
regression_model.fit(X_train , y_train)

LinearRegression()

In [46]:
for i, col_name in enumerate(X_train.columns):
    print(f"The coefficients for {col_name} is {regression_model.coef_[i]}")

The coefficients for cylinders is -0.2810786885876011
The coefficients for displacement is 0.026703935535847375
The coefficients for horsepower is -0.013024792305104178
The coefficients for weight is -0.007729286731383511
The coefficients for acceleration is 0.10184320216973305
The coefficients for model_year is 0.8599271950534446
The coefficients for origin is 1.555243686052706

In [47]:
#observations
#The coefficients are relatively smaller, if one independent variable changes slightly
#then there will be no much difference in prediction
#This is sometime called smoother models

In [48]:
from sklearn.metrics import r2_score
y_pred_linear = regression_model.predict(X_test)
y_pred_linear

array([21.07143702, 28.0234187 , 20.51738318, 27.22936913, 24.43614969,
       15.91628685, 30.04174133, 34.11886104, 17.00091169, 10.57481615,
       30.56157279, 16.57804388, 22.44332054, 27.75432974, 36.14332316,
       23.69730238, 10.8368185 , 20.25019623,  8.8467707 , 32.67849722,
       25.44799831, 32.80469133, 20.92380431, 24.49107207, 25.91379069,
       30.36646385, 32.08720589, 32.09185845, 15.14630201, 30.40163509,
       27.6835887 , 11.01554753, 21.48050983, 28.05328825, 24.97530397,
       13.77484711, 26.73912883,  9.14621132, 31.89119865, 23.90334337,
       24.19883104, 24.53222794, 21.19098163, 34.54725612, 26.36227571,
       22.22085501, 21.16462781, 11.59842875, 27.9359672 , 18.93572773,
       23.63114487, 26.84047743, 16.99134717, 11.99017011, 28.7549107 ,
       24.3322808 , 10.27131645, 13.00401997, 30.04141523, 35.38982215,
       37.14236105, 35.46111239, 18.05314404, 27.92346894, 20.76375532,
       33.88082058, 27.0109017 , 26.80000398, 29.94161767, 12.33979351,
       20.58414675, 22.59390737, 14.40926183, 26.4374455 , 11.55700374,
       25.53665115, 28.63093508, 16.5128925 , 11.61878372, 24.49413098,
       21.57961734, 20.87970628, 35.2389384 , 23.95107843, 34.20235086,
       18.42454089, 15.20517381, 23.89949006, 36.19499491, 33.17502084,
       19.87887572, 22.59567111, 20.83633131, 27.17806899, 31.85466982,
       22.49958083, 32.74444937, 29.00538119, 22.94175484, 24.32539402])

In [49]:
r2_linear = r2_score(y_test, y_pred_linear)
print(f"The R square of linear regression {r2_linear}")

The R square of linear regression 0.8346069296676931

In [50]:
from sklearn.linear_model import Ridge

In [51]:
ridge_regression_model = Ridge(alpha = 0.1)
ridge_regression_model

Ridge(alpha=0.1)

In [52]:
ridge_regression_model.fit(X_train, y_train)

Ridge(alpha=0.1)

In [53]:
for i, col_name in enumerate(X_train.columns):
    print(f"The coefficients for {col_name} is {ridge_regression_model.coef_[i]}")

The coefficients for cylinders is -0.2805447790089456
The coefficients for displacement is 0.026680958398890488
The coefficients for horsepower is -0.013019653943561013
The coefficients for weight is -0.007728789124042414
The coefficients for acceleration is 0.10179056877132633
The coefficients for model_year is 0.8598384800855792
The coefficients for origin is 1.5536485190948957

In [54]:
#if you compare the coefficient with earlier built model, the coefficient is reduced >> ridge regression
#Ridge regression evaluation
y_pred_ridge = ridge_regression_model.predict(X_test)
y_pred_ridge

array([21.0732006 , 28.02080567, 20.51723387, 27.22794191, 24.43606592,
       15.9157444 , 30.0407252 , 34.11852149, 17.00123484, 10.57499769,
       30.56210057, 16.57901826, 22.44311755, 27.75277179, 36.14306708,
       23.69594239, 10.83559645, 20.25137132,  8.84550759, 32.67832749,
       25.44794368, 32.8031025 , 20.92500697, 24.49175663, 25.91418116,
       30.36472831, 32.08667217, 32.09184353, 15.14722985, 30.40183027,
       27.6844489 , 11.0139232 , 21.4791362 , 28.05276738, 24.97603523,
       13.77477811, 26.74078953,  9.14451536, 31.89184357, 23.90437556,
       24.20083588, 24.53323508, 21.19103922, 34.54524825, 26.36367386,
       22.22114355, 21.16443626, 11.59853629, 27.93617155, 18.93589364,
       23.63191815, 26.84102909, 16.99088811, 11.99012164, 28.75650842,
       24.33284423, 10.27006102, 13.00391809, 30.0416382 , 35.38945238,
       37.14010207, 35.46070578, 18.05351684, 27.92469219, 20.76271618,
       33.87902334, 27.01233181, 26.80042366, 29.94223254, 12.34032053,
       20.58324968, 22.59556659, 14.40963051, 26.43866534, 11.55771698,
       25.53875629, 28.62922441, 16.51303281, 11.61862642, 24.49304311,
       21.57842801, 20.87740107, 35.2384352 , 23.95262724, 34.20183433,
       18.42351274, 15.20561865, 23.89952027, 36.19315216, 33.1732649 ,
       19.87799057, 22.59601697, 20.83730916, 27.17533566, 31.85330374,
       22.5000123 , 32.74405084, 29.00413022, 22.94205556, 24.3254517 ])

In [55]:
r2_ridge = r2_score(y_test, y_pred_ridge)
print(f"The R square of ridge regression {r2_ridge}")

The R square of ridge regression 0.8346217481568861

In [56]:
#we dont see much variation is coeff of ridge regression as compared to linear regression

In [57]:
#Lasso regression
from sklearn.linear_model import Lasso
lasso_regression_model = Lasso(alpha = 0.5)
lasso_regression_model.fit(X_train, y_train)

Lasso(alpha=0.5)

In [58]:
for i, col_name in enumerate(X_train.columns):
    print(f"The coefficients for {col_name} is {lasso_regression_model.coef_[i]}")

The coefficients for cylinders is -0.0
The coefficients for displacement is 0.006262810460624523
The coefficients for horsepower is -0.011112514442916424
The coefficients for weight is -0.007015211064365715
The coefficients for acceleration is 0.0
The coefficients for model_year is 0.7520794799469872
The coefficients for origin is 0.0

In [59]:
#3 features coefficient are 0, Lasso helps in feature selection

In [60]:
y_pred_lasso = lasso_regression_model.predict(X_test)
r2_lasso = r2_score(y_test, y_pred_lasso)
print(f"The R square of lasso regression {r2_lasso}")

The R square of lasso regression 0.8312434767529662

In [61]:
from sklearn.linear_model import ElasticNet
elastic_net_model = ElasticNet(alpha = 1, l1_ratio = 0.5)
elastic_net_model.fit(X_train, y_train)

ElasticNet(alpha=1)

In [62]:
for i, col_name in enumerate(X_train.columns):
    print(f"The coefficients for {col_name} is {elastic_net_model.coef_[i]}")

The coefficients for cylinders is -0.0
The coefficients for displacement is 0.005703783119559165
The coefficients for horsepower is -0.012320446698032825
The coefficients for weight is -0.006950341501956362
The coefficients for acceleration is 0.0
The coefficients for model_year is 0.7194419476598072
The coefficients for origin is 0.0

In [63]:
# Predict on the test set
y_pred_elastic_net = elastic_net_model.predict(X_test)

# Calculate evaluation metrics
r2_elastic_net = r2_score(y_test, y_pred_elastic_net)


print(f"R-squared score for Elastic Net Regression: {r2_elastic_net}")

R-squared score for Elastic Net Regression: 0.832835938176032